/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class Library {

    public static void main(String[] args) {

        LinkedList linkedList = new LinkedList(new Node(7,null));

        linkedList.insert(new Node(8,null));
        linkedList.insert(new Node(9,null));

        linkedList.view();

        if(linkedList.isInclude(linkedList.head, 7)){
            System.out.println("It is include");
        }else{
            System.out.println("It is NOT include");
        }

        if(linkedList.isInclude(linkedList.head, 10)){
            System.out.println("It is include");
        }else{
            System.out.println("It is include");
        }

        System.out.println(linkedList.stringPath());



    }
}
