/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sort;

import Sort.Insertion.InsertionSort;
import Sort.Merge.MergeSort;

import java.util.Arrays;

public class App {

    public static void main(String[] args) {

//        <<< COde Challenge 26 >>>

        int[] arr = {8, 4, 23, 42, 16, 15};

        InsertionSort insertionSort = new InsertionSort();
        insertionSort.insertionSort(arr);

        System.out.println(Arrays.toString(arr));

        //        <<< COde Challenge 27 >>>

        int [] mergeArr = {8, 4, 23, 42, 16, 15};
        MergeSort mergeSort = new MergeSort();

        mergeSort.mergeSort(mergeArr);
        System.out.println("Merge Array " + Arrays.toString(mergeArr));
    }


}
